# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

messinaC <- function(x, cls, n_boot, n_train, minsens, minspec, progress, silent) {
    .Call('messina_messinaC', PACKAGE = 'messina', x, cls, n_boot, n_train, minsens, minspec, progress, silent)
}

messinaSurvCoxph <- function(cls, times, events, tol, maxiter) {
    .Call('messina_messinaSurvCoxph', PACKAGE = 'messina', cls, times, events, tol, maxiter)
}

